spring.application.name=UrbanMart

#Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/urbanmart
spring.datasource.username=urbanmart_user
spring.datasource.password=urbanmart_password
spring.datasource.driver-class-name=org.postgresql.Driver

#Spring Data JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#JWT
jwt.secret=day-la-chuoi-bi-mat-cua-ban-can-du-dai-it-nhat-32-ky-tu-doi-thanh-gia-tri-that
jwt.expiration-ms=86400000